---
title: "RUVPRPS-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ggplot2)
library(SummarizedExperiment)
library(BiocSingular)
library(ggpubr)
library(cowplot)
library(scales)
library(gridExtra)
library(RUVPRPS)
```

```{r load data}
# file_remote="https://zenodo.org/record/6326542/files/READ%20%28Rectum%20adenocarcinoma%29.rds"
# # Make temp local copy
# file_local <- basename(file_remote)
# file_local <- file.path(tempdir(), file_local)
# options(timeout=1000)
# download.file(file_remote, file_local, quiet = F)
# # Load file
# data<- readRDS(file_local)

```



```{r RUVPRPS Norm data}

```

```{r Merge all datasets}
# ### Merge all datasets together
# raw.count.data <- SummarizedExperiment::assay(skcm.se,'HTseq_counts')
# row.names(ruviii.prps.norm) <- as.data.frame(SummarizedExperiment::rowData(skcm.se))$gene_name.
# skcm.se.log <- SummarizedExperiment::SummarizedExperiment(assays = list(
#     HTseq_counts = log2(SummarizedExperiment::assay(
#       skcm.se,
#       'HTseq_counts') + 1),
#     HTseq_FPKM = log2(SummarizedExperiment::assay(
#       skcm.se,
#       'HTseq_FPKM') + 1),
#     HTseq_FPKM.UQ = log2(SummarizedExperiment::assay(
#       skcm.se,
#       'HTseq_FPKM.UQ') + 1),
#     RUV_III = ruviii.prps.norm
#   ),
#   colData = S4Vectors::DataFrame(
#     SummarizedExperiment::colData(skcm.se)),
#   rowData = as.data.frame(
#     SummarizedExperiment::rowData(skcm.se))
# )
# skcm.sampleAnnot <- as.data.frame(
#   SummarizedExperiment::colData(skcm.se))
# 
# normalizations <- names(
#   SummarizedExperiment::assays(skcm.se)
# )
# normalizations.names <- c(
#   'Raw counts',
#   'FPKM',
#   'FPKM.UQ',
#   'RUV-PRPS')
```

```{r Assessment of the normalisations}
# ### Generate all plots 
# all_plots=norm_assessment(skcm.se.log,
#     apply.log = FALSE,
#     skcm.se.log$subtype_differentiation,
#     skcm.se.log$libSize,
#     skcm.se.log$PlateId_mda,
#     output_file=paste0(wd,"test_pca.pdf"))
# 
# ## Plot based on Biology
# do.call(grid.arrange,
#   c(all_plots$plot_bio,
#     ncol = 4))
# ## Plot based on Time
# do.call(grid.arrange,
#       c(all_plots$plot_time,
#           ncol = 4))
