# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastResidop <- function(A, B) {
    .Call('_RUVPRPS_fastResidop', PACKAGE = 'RUVPRPS', A, B)
}

fastResidop2 <- function(A, B) {
    .Call('_RUVPRPS_fastResidop2', PACKAGE = 'RUVPRPS', A, B)
}

matrixMult <- function(A, B) {
    .Call('_RUVPRPS_matrixMult', PACKAGE = 'RUVPRPS', A, B)
}

matSubtraction <- function(A, B) {
    .Call('_RUVPRPS_matSubtraction', PACKAGE = 'RUVPRPS', A, B)
}

matTranspose <- function(A) {
    .Call('_RUVPRPS_matTranspose', PACKAGE = 'RUVPRPS', A)
}

matInverse <- function(A) {
    .Call('_RUVPRPS_matInverse', PACKAGE = 'RUVPRPS', A)
}

